version: "3.4"
services:
    nopcommerce_web:
        build: .
        container_name: nopcommerce
        # ports:
        #     - "8081:80"
        depends_on:
            - nopcommerce_database
    nopcommerce_database:
        image: "postgres:latest"
        container_name: nopcommerce_database
        restart: "always"
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
          POSTGRES_PASSWORD: "nopCommerce"
          POSTGRES_USER: "nopCommerce"
          POSTGRES_DB: "nopCommerce"
    reverse-proxy:
        image: nginx:1.17.10
        container_name: reverse_proxy
        depends_on:
            - nopcommerce_web
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80


volumes:
  nopcommerce_data:  
  postgres-data:
    external: true